### ISSUE TITLE
Error:  Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by geeaqui** [SimitTomar/wdio-cucumber-parallel-execution#17]
Hi @SimitTomar , 

I have recently started using the library and noticed an intermittent error at the beginning of the tests execution `Error: ENOTEMPTY: directory not empty, rmdir`. Although there was an error, a temporary folder is successfully created for which contains the split scenarios and the tests run successfully. Any idea what might cause this?

```
Error:  Error: ENOTEMPTY: directory not empty, rmdir '<path-to-tmp-folder>'
    at Object.rmdirSync (fs.js:890:10)
    at rmkidsSync (rimraf/rimraf.js:364:25)
    at rmdirSync (rimraf/rimraf.js:342:7)
    at Function.rimrafSync [as sync] (rimraf/rimraf.js:312:9)
    at Object.removeSync (wdio-cucumber-parallel-execution/node_modules/fs-extra/lib/remove/index.js:4:17)
    at Object.performSetup (wdio-cucumber-parallel-execution/performSetup.js:26:22)
    at Object.<anonymous> (config/wdio.conf.ts:17:55)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (ts-node/src/index.ts:1056:23) {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '<path-to-tmp-folder>/tmp'
}
```

**Current set-up:**
wdio version: 6.4.0
@wdio/browserstack-service: 6.4.0
@wdio/cucumber-framework: 6.4.0
Number of tests running in parallel: 5

**Comment by VitaliLebedzeu** [comment]
The same issue. I think the suggestions from this [PR #20](https://github.com/SimitTomar/wdio-cucumber-parallel-execution/pull/20) should fix this problem
